### ISSUE TITLE
Not able to run feature file using testng

### ISSUE THREAD

**Issue by VijenderChhokar** [VijenderChhokar/Cucumber-Issues#1]
I was trying to run my feature file using testng. But  i am getting the below error.
1. Feature file name : GmailLogin.feature
2. Created runner class(GmailLoginFeatureRunner) to run this feature file and code given below:
package runner;
import cucumber.api.CucumberOptions;
import cucumber.api.testng.AbstractTestNGCucumberTests;

@CucumberOptions(features = {"D:\\Selenium\\Automate_Oxygen\\CucumberTest\\src\\test\\resources\\featureFile\\GmailLogin.feature"})
public class GmailLoginFeatureRunner extends AbstractTestNGCucumberTests {

}

3. Created testng.xml file and i have added the below class name in testng.xml file

class name="runner.GmailLoginFeatureRunner"
   

  

[RemoteTestNG] detected TestNG version 6.14.2
org.testng.TestNGException: 
Cannot find class in classpath: runner.GmailLoginFeatureRunner
	at org.testng.xml.XmlClass.loadClass(XmlClass.java:77)
	at org.testng.xml.XmlClass.init(XmlClass.java:69)
	at org.testng.xml.XmlClass.<init>(XmlClass.java:55)
	at org.testng.xml.TestNGContentHandler.startElement(TestNGContentHandler.java:575)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(XMLDTDValidator.java:766)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.testng.xml.XMLParser.parse(XMLParser.java:38)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:16)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:9)
	at org.testng.xml.Parser.parse(Parser.java:152)
	at org.testng.xml.Parser.parse(Parser.java:233)
	at org.testng.TestNG.parseSuite(TestNG.java:295)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:348)
	at org.testng.TestNG.initializeEverything(TestNG.java:995)
	at org.testng.remote.support.RemoteTestNG6_12.initialize(RemoteTestNG6_12.java:22)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:97)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by VijenderChhokar** [comment]
[CucumberTest.zip](https://github.com/VijenderChhokar/Cucumber-Issues/files/1958499/CucumberTest.zip)
 
This is my project code.
